[package]
name = "maomi"
version = "0.1.0"
authors = ["LastLeaf <bqfu@163.com>"]
license = "MIT"
description = "A rust wasm framework for building pages with components"
homepage = "https://github.com/LastLeaf/maomi"
documentation = "https://github.com/LastLeaf/maomi"
repository = "https://github.com/LastLeaf/maomi"
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
me-cell = { version = "=0.1.0", path = "../me-cell" }
maomi-macro = { version = "=0.1.0", path = "../maomi-macro" }
wasm-bindgen = "0.2"
console_error_panic_hook = "0.1"
js-sys = "0.3"
log = "0.4"
console_log = "0.1"
downcast-rs = "1.1"
futures = "0.3"
serde = { version = "1.0", features = ["derive"] }
bincode = "1.2"
base64 = "0.11"

[dependencies.web-sys]
version = "0.3"
features = [
  "Window",
  "Document",
  "HtmlElement",
  "Node",
  "NodeList",
  "Element",
  "Text",
  "Comment",
  "DocumentFragment",
  "EventListener",
  "EventTarget",
  "Event",
  "MouseEvent",
  "TouchEvent",
  "TouchList",
  "Touch",
  "KeyboardEvent"
]

[dev-dependencies]
wasm-bindgen-test = "0.3"
