[workspace]
members = [
    "maomi",
    "maomi-macro",
    "maomi-tree",
    "maomi-skin",
    "maomi-dom",
    "maomi-dom-macro",
    "maomi-dom-template",
]

[profile.release]
opt-level = "z"
