[package]
name = "maomi"
version = "0.1.0"
authors = ["LastLeaf <bqfu@163.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
me-cell = { path = "./me-cell" }
maomi-macro = { path = "./macro" }
wasm-bindgen = "0.2"
console_error_panic_hook = "0.1"
js-sys = "0.3"

[dependencies.web-sys]
version = "0.3"
features = ["Window", "Document", "HtmlElement", "Element", "Text", "Node", "NodeList", "Comment"]

[dev-dependencies]
wasm-bindgen-test = "0.2"

[profile.release]
opt-level = "s"
