[workspace]
members = [
    "maomi",
    "maomi-macro",
    "maomi-skin",
    "lazy-observer",
    "me-cell",
    "examples/hello-world",
    "examples/event-handling",
]

[profile.release]
opt-level = "s"
