#[derive(Debug)]
pub enum Error {
    /// A custom error
    ///
    /// Generally refers to errors generated by other crates.
    Custom(Box<dyn std::error::Error>),
    /// The operation is invalid before component created
    TreeNotCreated,
    /// A wrong backend tree is visited
    ///
    /// Generally refers to some bad operation being done directly in the backend.
    TreeNodeTypeWrong,
    /// The backend tree node has been released
    ///
    /// Generally refers to some bad operation being done directly in the backend.
    TreeNodeReleased,
    /// A list update failed due to wrong changes list
    ListChangeWrong,
    /// A recursive update is detected
    ///
    /// An element cannot be updated while it is still in another update process.
    RecursiveUpdate,
    /// The backend context is already entered
    AlreadyEntered,
    /// A general backend failure
    BackendError {
        msg: String,
        err: Option<Box<dyn std::error::Error>>,
    },
}

impl std::fmt::Display for Error {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Error::Custom(err) => {
                write!(f, "{}", err)?;
            }
            Error::TreeNotCreated => {
                write!(f, "Component template has not been initialized")?;
            }
            Error::TreeNodeTypeWrong => {
                write!(f, "The node type in backend element tree is incorrect")?;
            }
            Error::TreeNodeReleased => {
                write!(f, "The node in backend element tree has been released")?;
            }
            Error::ListChangeWrong => {
                write!(f, "The list change is incorrect")?;
            }
            Error::RecursiveUpdate => {
                write!(f, "A recursive update is detected")?;
            }
            Error::AlreadyEntered => {
                write!(f, "The backend context is already entered")?;
            }
            Error::BackendError { msg, err } => {
                if let Some(err) = err {
                    write!(f, "{}: {}", msg, err.to_string())?;
                } else {
                    write!(f, "{}", msg)?;
                }
            }
        }
        Ok(())
    }
}

impl std::error::Error for Error {}
